from __future__ import annotations

from pathlib import Path

import config
from services.codegen.estimate import parse_gcode_estimate
from slicer_service import _slice_mesh


def test_parse_prusaslicer_time_material_and_cost(tmp_path: Path) -> None:
    gcode = tmp_path / "model.gcode"
    gcode.write_text(
        "; generated by PrusaSlicer\n"
        "; estimated printing time (normal mode) = 1h 15m 30s\n"
        "; filament used [g] = 20.0\n"
        "; filament used [cm3] = 16.2\n"
    )

    estimate = parse_gcode_estimate(gcode)

    assert estimate is not None
    assert estimate.print_minutes == 75.5
    assert estimate.filament_g == 20.0
    assert estimate.filament_cm3 == 16.2
    assert estimate.cost_usd == 0.5


def test_slice_mesh_runs_headless_cli(tmp_path: Path, monkeypatch) -> None:
    slicer = tmp_path / "prusa-slicer"
    slicer.write_text(
        "#!/bin/sh\n"
        "while [ $# -gt 0 ]; do\n"
        "  if [ \"$1\" = \"--output\" ]; then shift; printf '; ok\\n' > \"$1\"; fi\n"
        "  shift\n"
        "done\n"
    )
    slicer.chmod(0o755)
    stl = tmp_path / "model.stl"
    stl.write_text("solid test\nendsolid test\n")
    gcode = tmp_path / "model.gcode"
    object.__setattr__(config.settings, "prusaslicer_path", str(slicer))

    assert _slice_mesh(stl, gcode, profile_id="generic_fdm_04mm") is True
    assert gcode.exists()


def test_prusaslicer_29_zero_grams_falls_back_to_volume_density(tmp_path: Path) -> None:
    gcode = tmp_path / "large.gcode"
    gcode.write_text(
        ("G1 X1 Y1\n" * 5_000)
        + "; estimated printing time (normal mode) = 2h 5m 0s\n"
        "; filament used [cm3] = 10.0\n"
        "; total filament used [g] = 0.00\n"
        + ("; config = value\n" * 10_000)
    )

    estimate = parse_gcode_estimate(gcode)

    assert estimate is not None
    assert estimate.print_minutes == 125.0
    assert estimate.filament_g == 12.4
